// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-balance.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var EXCHANGE_RATE = 150;
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_balance_default = defineTool({
  name: "get_balance",
  title: "Get balance",
  description: "Return the signed-in user's available balance (deposits + profits \u2212 withdrawals) in USD and KES.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [dep, wd] = await Promise.all([
      sb.from("deposits").select("amount_usd, profit_amount, status").eq("user_id", userId),
      sb.from("withdrawals").select("amount_usd, status").eq("user_id", userId)
    ]);
    if (dep.error) return { content: [{ type: "text", text: dep.error.message }], isError: true };
    if (wd.error) return { content: [{ type: "text", text: wd.error.message }], isError: true };
    const deposited = (dep.data ?? []).filter((d) => d.status === "completed").reduce((s, d) => s + Number(d.amount_usd || 0) + Number(d.profit_amount || 0), 0);
    const withdrawn = (wd.data ?? []).filter((w) => w.status !== "rejected").reduce((s, w) => s + Number(w.amount_usd || 0), 0);
    const balanceUsd = Math.max(0, deposited - withdrawn);
    const balanceKes = Math.round(balanceUsd * EXCHANGE_RATE);
    return {
      content: [{ type: "text", text: `Available balance: $${balanceUsd.toFixed(2)} (\u2248 KES ${balanceKes})` }],
      structuredContent: { balance_usd: balanceUsd, balance_kes: balanceKes }
    };
  }
});

// src/lib/mcp/tools/list-deposits.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deposits_default = defineTool2({
  name: "list_deposits",
  title: "List deposits",
  description: "List the signed-in user's deposits, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("deposits").select("id, amount_usd, profit_amount, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { deposits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-withdrawals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_withdrawals_default = defineTool3({
  name: "list_withdrawals",
  title: "List withdrawals",
  description: "List the signed-in user's withdrawals, most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("withdrawals").select("id, amount_usd, status, mpesa_phone, admin_notes, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { withdrawals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-gold-price.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_gold_price_default = defineTool4({
  name: "get_gold_price",
  title: "Get gold price",
  description: "Fetch the current live spot price of gold (XAU/USD) per troy ounce.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async () => {
    try {
      const res = await fetch("https://api.gold-api.com/price/XAU");
      if (!res.ok) throw new Error(`gold-api returned ${res.status}`);
      const data = await res.json();
      const price = Number(data?.price);
      const pricePerGram = price / 31.1035;
      return {
        content: [
          {
            type: "text",
            text: `Gold (XAU/USD): $${price.toFixed(2)}/oz (\u2248 $${pricePerGram.toFixed(2)}/g)`
          }
        ],
        structuredContent: { price_per_ounce_usd: price, price_per_gram_usd: pricePerGram }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed to fetch gold price: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/request-withdrawal.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var request_withdrawal_default = defineTool5({
  name: "request_withdrawal",
  title: "Request withdrawal",
  description: "Submit a withdrawal request for the signed-in user to be paid out via M-Pesa.",
  inputSchema: {
    amount_usd: z3.number().positive().describe("Amount to withdraw in USD."),
    mpesa_phone: z3.string().min(9).describe("M-Pesa phone number to receive the payout.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ amount_usd, mpesa_phone }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("withdrawals").insert({
      user_id: ctx.getUserId(),
      amount_usd,
      mpesa_phone: mpesa_phone.trim(),
      status: "pending"
    }).select("id, amount_usd, mpesa_phone, status, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Withdrawal requested: $${amount_usd} to ${mpesa_phone} (status: ${data.status})` }],
      structuredContent: { withdrawal: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "deurylywogvzxgpbunqi";
var mcp_default = defineMcp({
  name: "kenya-smart-trades-mcp",
  title: "Kenya Smart Trades",
  version: "0.1.0",
  instructions: "Tools for the Kenya Smart Trades trading app. Callers act as the signed-in user. Use `get_balance`, `list_deposits`, and `list_withdrawals` to inspect the account, `get_gold_price` for the live XAU/USD spot price, and `request_withdrawal` to submit an M-Pesa payout request.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_balance_default, list_deposits_default, list_withdrawals_default, get_gold_price_default, request_withdrawal_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
